### ISSUE TITLE
Make resource requests and limits configurable

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#10]
Default Helm charts offer an ability to configure resource limits:

```bash
  resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 32Mi
    # requests:
    #   cpu: 10m
    #   memory: 32Mi
```

I think this is required for production environments here as well.

https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L273

**Comment by S-Nigel** [comment]
Thanks for your suggestion!
I have made the resource requests and limits configurable in the `values.yaml` for: auth, image, api, frontend and adminer.
