### ISSUE TITLE
Share code adjustments 

### ISSUE THREAD

**Issue by jaapgorjup** [Amsterdam/openstad-kubernetes#20]
Collect all code changes/adjustments needed including those for more inclusive logging to support problem fixing in product environments.
Supply these as pull request

**Comment by diederikgithub** [comment]
@ToshKoevoets: I can  not push to the  Amsterdam / openstad-frontend repo. Could you please provide me access so I can create branches and make pull-requests?

**Comment by ToshKoevoets** [comment]
Hi Diederik,

Easiest way is too fork amsterdam repo (on github) and make a PR from that
repo.

Gr. Tosh

Op di 16 jun. 2020 om 14:07 schreef diederikgithub <notifications@github.com

**Comment by ToshKoevoets** [comment]
If you dont have a repo on github, you can just add a github remote to your
current repo and push it, and make a PR from that repo to amsterdam repo

Op di 16 jun. 2020 om 14:57 schreef Tosh Koevoets <tosh.koevoets@gmail.com>:

**Comment by diederikgithub** [comment]
Ok, thank you! I forked the repo and created a pull request (at least, I think I did). Hope this is the way to do it.

**Comment by ToshKoevoets** [comment]
yes perfect! thanks

Op di 16 jun. 2020 om 15:46 schreef diederikgithub <notifications@github.com
