### ISSUE TITLE
For the API execute reset only the first time and in other situations use migrate

### ISSUE THREAD

**Issue by jaapgorjup** [Amsterdam/openstad-kubernetes#23]
Currently using the reset in the init-container clears the database needlessly.
Please ensure this is done only the first time to create it.
Also take care that the right fixtures are loaded so the database configuration will match.

Please document all exceptional situations in [docs/database.md]

**Comment by diederikgithub** [comment]
Running migrate script on install might be tricky, as the database could already be there.
A working solution is that we run migrate.js at the init-container and that we run the reset.js manually if needed with `kubectl exec openstad-api-<pod-id> -- node reset.js`. Is this acceptable?

**Comment by ToshKoevoets** [comment]
Not possible with the post install hook like discussed?

For example: https://helm.sh/docs/topics/charts_hooks/#writing-a-hook

Op di 16 jun. 2020 om 13:18 schreef diederikgithub <notifications@github.com

**Comment by diederikgithub** [comment]
Ok, I'll make it a post-install hook. I was just worried what would happen if you install first time against existing my-sql database. But maybe that's a none issue.

**Comment by diederikgithub** [comment]
I added the reset database as post-install hook. The init-container of api runs a migrate. At first install the migrate fails until the post-install hook is executed, but eventually everything is up and running.

**Comment by ToshKoevoets** [comment]
Yeah currently not an issue and can't imagine that being an issue. Also at
same time we will fix the reset script to only run if exists so then also
that scenario will be covered

Op wo 17 jun. 2020 om 09:44 schreef diederikgithub <notifications@github.com

**Comment by ToshKoevoets** [comment]
@diederikgithub can wel close this issue? It seems to be implemented

**Comment by diederikgithub** [comment]
Yes it is implemented as it looks like you verified it I close the issue
