### ISSUE TITLE
openssl delete

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#26]
Currently in Dockerfile openssl is being removed . Yet it's necessary because certificates generated is after. How is it working in k8s? Is using openssl from other system?

```
# Remove unused packages only used for building.
RUN apk del openssl g++ make && rm -rf /var/cache/apk/*
```

**Comment by S-Nigel** [comment]
Hello @ToshKoevoets,

If it is later installed again in the same container, it shouldn't be removed in the first place. Otherwise other containers must provide their own software such as OpenSSL in their own environment/container. 

This way the different containers don't depend on software from other containers and they can be updated or removed easier without breaking other pods/containers.
Each image/container kinda becomes a self-contained micro-system on its own.

**Comment by ToshKoevoets** [comment]
Ok so this is then issue with docker file. Im also running into permission
issue not being allowed to access cert dir

**Comment by ToshKoevoets** [comment]
@S-Nigel I have fixed this in Dockerfile in auth repo so will let you know but I think we can close it, but want to install a new cluster once to see if my new development containers will manage

**Comment by diederikgithub** [comment]
@ToshKoevoets: I did remove the generation of certificates from the docker file in the auth, as there should not be private keys in a docker image especially not when the image is stored in a public registry. Certificates are now generated installation time during pre-install (with a bitnami/kubectl docker image) and stored in a secret that is mounted by the auth container. Does the container also generates certificates at runtime?

**Comment by ToshKoevoets** [comment]
@diederikgithub yes I saw, and you are completely right. I ran into it because I need certs for running tests, but now I package test-certificates that is not really security issue.

I was just wondering how it's possible k8s is generating openssl certificates if openssl is not present in the container. So either you are using openssl from k8s or container is created by other Dockerfile

**Comment by diederikgithub** [comment]
@ToshKoevoets: For test is fine. We don't maintain the docker files in this repo anymore, I deleted them. So you can adjust the removal of openssl in the dockerfile of the auth-repo if you still need it.

**Comment by diederikgithub** [comment]
@ToshKoevoets: Can we close this issue?
