### ISSUE TITLE
Helm install errors on different namespace then openstad

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#27]
Trying to create 
`helm install --values c-values.yaml --replace openstad . --namespace=openstad-development --create-namespace --set clusterIssuer.enabled=false`

`
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "openstad-cert-manager-cainjector" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "openstad-development": current value is "openstad"
`

I deleted ns, but seems it is error on an existing release?

**Comment by S-Nigel** [comment]
Hello @ToshKoevoets,

Thanks for reporting this issue. The problem seems to be related to what we found in issue #31 .
After uninstalling the chart and after removing cert-manager including its CRD's. Does this still happen?

I tried it on Hetzner Cloud and got the following:
```
$ helm install openstad . --namespace openstad-development --create-namespace
NAME: openstad
LAST DEPLOYED: Mon Jun 22 14:16:55 2020
NAMESPACE: openstad-development
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

This was directly after having installed it on the `openstad` namespace followed by uninstalling the chart (whilst keeping the namespace).

If this issue still exists let me know!

**Comment by ToshKoevoets** [comment]
Thanks will test coming days!

Op ma 22 jun. 2020 om 14:21 schreef Nigel <notifications@github.com>:

**Comment by ToshKoevoets** [comment]
@S-Nigel I wanted to run release and development in different namespaces. I realise that's not possible this way.

**Comment by S-Nigel** [comment]
Hello @ToshKoevoets,

The current default setup/chart does not allow for multiple instances (production + development) on the same cluster.
It may be possible if you disable all CRD installations (cert-manager) in the second instance as CRD's are global. 

Currently, I think this is out of scope, maybe more suitable as a documentation/installation note.

In other words:

> is this possible with running cluster wide cert manager?

If I'm not mistaken yes. It should also be doable by just installing the CRD's on one of the instances, preferable production (Helm uninstall gets rid of the CRD and all resources using the relevant CRD's).

**Comment by ToshKoevoets** [comment]
Hi Nigel, we were having discussions here that it would be to install the
cert manager cluster wide and properly document how to do it, same as
nginx, this would solve most problems also with uninstall.

Op wo 24 jun. 2020 om 10:32 schreef Nigel <notifications@github.com>:

**Comment by S-Nigel** [comment]
Hi @ToshKoevoets,

Awesome! In that case, can we close this issue for now? Or shall we wait till the documentation is in place?
