### ISSUE TITLE
Runnen setEnables

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#28]
I'm wondering what is the right way to update cluster values.

The current way that is described in the documentation to update the custerIssuer value removes all custom values:

```
helm upgrade openstad . --namespace openstad --set clusterIssuer.enabled=true
```

This empties all values and the urls don't work anymore.

Updating the initial config file and changing it there does work:

```
helm upgrade -f custom-values.yaml openstad . -n openstad
```

**Comment by S-Nigel** [comment]
I was able to use both the custom-values.yaml and set the values for the cluster issuer in my test:
```
helm install openstad . --namespace openstad --create-namespace --values custom-values.yaml --set clusterIssuer.enabled=true
```

**Comment by S-Nigel** [comment]
I believe the problem here is that the documentation doesn't state how to do this with custom-values.yaml. I will update it

**Comment by S-Nigel** [comment]
As far as I know and have tested both `--values` and `--set` can be used in the `helm install` command. I have added a note in 40ede74

If this wasn't the problem or if it doesn't work on your end please reopen this issue.
