### ISSUE TITLE
Use Release.namespace

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#3]
It is considered best practice to use `{{ .Release.namespace }}` for namespaces of Helm releases.

In some cases Helm values are used currently, e.g.: 

https://github.com/Amsterdam/openstad-kubernetes/blob/3715f45a8bac0094c872c3f396679edd4249a698/k8s/openstad-chart/templates/frontend/deployment.yaml#L7

**Comment by S-Nigel** [comment]
I have replaced all the references to Helm values regarding namespaces to `{{ .Release.namespace }}`. Thanks for the input!

**Comment by bartjkdp** [comment]
Thanks for fixing this!
