### ISSUE TITLE
SESSION_SECRET's are hardcoded

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#30]
```
          - name: SESSION_SECRET
            value: "1234567890123456"
```

**Comment by ToshKoevoets** [comment]
Is it possible to autogenerate a string on install?

**Comment by S-Nigel** [comment]
I don't know how to do that yet. If everything goes according to plan I'll pick this issue up next Wednesday (24-06-2020)

I think it is possible but haven't looked into it yet.

**Comment by S-Nigel** [comment]
I have replaced all secrets I could find with random alphanumeric strings with a length of 12.

If you spot any I missed, or if I missed a place where the same random secret should have been put, please reopen this issue.

**Comment by S-Nigel** [comment]
For later reference:
```yaml
     {{ randAlphaNum 12 | quote }} 
```
Gives a random alphanumeric string with the size of 12 characters

**Comment by ToshKoevoets** [comment]
I understood the problem with this is that they get random generated every
new release? Is that correct? If so, this might cause issues in some cases.

Op wo 24 jun. 2020 om 11:00 schreef Nigel <notifications@github.com>:

**Comment by S-Nigel** [comment]
Hello @ToshKoevoets,

> I understood the problem with this is that they get random generated every new release?

The secrets are created at the first time the chart is installed. In my test, the secrets are kept at an uninstall and are only reset/deleted when you remove the namespace. Randomly generated passwords/secrets should only exist in the Kubernetes Secrets as they persists between upgrades and reinstalls.

If we generate a random secret in a deployment.yaml this gets randomized with every upgrade/release.
In resources with the resource-policy of keep, this is only done when it's first installed in the namespace.

**Comment by ToshKoevoets** [comment]
Okay that's perfect then.

Op wo 24 jun. 2020 om 11:45 schreef Nigel <notifications@github.com>:
