### ISSUE TITLE
Mongodb have to use old version for now

### ISSUE THREAD

**Issue by ToshKoevoets** [Amsterdam/openstad-kubernetes#42]
For mongodb we have to use an older version for now because they have removed the feature to copy a mongodb. Now they expect the code to dump and import manually.

We are discussing to write a custom copy function that solves this.

But for now we need to stay on the older version.

Locally I've fixed this by specifying the correct image in custom values.

Is there a way to add this to the requirements for now? Because reverting once installed doesn't seem very easy since volumes are created on install. 

```
mongodb:
  image:
    tag: 4.0.14-ol-7-r39
```

**Comment by diederikgithub** [comment]
mongodb is now set to 4.0.14-ol-7-r39
