### ISSUE TITLE
Image server does not persist uploaded images between restarts

### ISSUE THREAD

**Issue by rudivanhierden** [Amsterdam/openstad-kubernetes#56]
**Description**
Restarting the image server pod will result in a loss of uploaded images. The image server saves uploaded images to the /app/images directory, but this directory is not saved on a persistent volume. The persistent volume 'data-vol' is mounted in /home/app/data, but this folder is never used.

**Suggested fix**
The persistent volume 'data-vol' can be mounted under /app/images, which will make sure the uploaded images are persisted between restarts of the image-server pod.

Before upgrading an existing cluster, a backup should be made of the /app/images folder. After the upgrade the /app/images folder can be cleared and hydrated with the backup. It might be necessary to run an initContainer to set the correct owner on the /app/images folder so it can be written to.

Related ticket: https://trello.com/c/z3pKQ1G9/87-kubernetes-persistent-volume-voor-image-server

**Comment by ToshKoevoets** [comment]
@rudivanhierden This is merged, so will close this one.
