### ISSUE TITLE
Generate resource names based on release name

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#6]
It would be nice if resource names are generated based on release names. This is considered best practice when creating Helm charts, for an example see:

https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L14

and 

https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/_helpers.tpl#L16-L31

**Comment by S-Nigel** [comment]
Hello Bart, thanks for your feedback.
I have added a helper template for the resource names and replaced the old references. Please let me know what you think!

Feel free to open this issue again in case it's different then what you meant or if I missed some names.
