### ISSUE TITLE
Hardcoded namespace in persistence volume claim

### ISSUE THREAD

**Issue by bartjkdp** [Amsterdam/openstad-kubernetes#7]
The current persistent volume claim contains a hardcoded namespace. I think this should be `{{ .Release.Namespace }}` as well:

https://github.com/Amsterdam/openstad-kubernetes/blob/a50d71174b038ee9edee7fd11980e28cb9a79f98/k8s/openstad-chart/templates/persistence-claim.yml#L5

**Comment by S-Nigel** [comment]
Thanks for reporting the hardcoded namespaces. I have also removed the hardcoded namespace values in 17 other files. Let me know if you find more! :+1:
